name: CI Pipeline
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: simple-login/app.git
          ref: master
      - name: Install Node.js dependencies (npm)
        run: npm ci
      - name: Run JavaScript application
        run: npm start
