name: CI Pipeline
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем репозиторий
      - uses: actions/checkout@v3
        with:
          repository: prometheus/prometheus
          ref: main

      # Шаг 2: Установить Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Шаг 3: Скачать модули
      - name: Download Go modules
        working-directory: prometheus
        run: go mod download

      # Шаг 4: Запустить приложение
      - name: Run Go application
        working-directory: prometheus
        run: go run .
