 name: CI Pipeline
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: AbdiHaryadi/docx-word-checker.git
          ref: main
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run Python application
        run: python main.py
