name: CI Pipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: turtl/js.git
          ref: master
      - name: Detect project type and list files
        run: |
          echo "Project directory: $(pwd)"
          echo "Detected files:"
          find . -type f -name "*.json" -o -name "*.py" -o -name "*.go" -o -name "*.rs" -o -name "*.rb" | head -20
          echo "Root directory contents:"
          ls -la
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test --if-present
      
      - name: Build project
        run: npm run build --if-present
      
      - name: Security audit
        run: |
          if [ "npm" = "npm" ]; then
            npm audit --audit-level moderate || true
          elif [ "npm" = "yarn" ]; then
            yarn audit --level moderate || true
          fi

      - name: Pipeline completion
        run: |
          echo "✅ CI Pipeline completed successfully"
          echo "Project type: javascript"
          echo "Branch: master"
          date
