name: CI Pipeline
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: prometheus/prometheus.git
          ref: main
      - name: Download Go modules
        working-directory: prometheus
        run: go mod download
    
      - name: Run Go application
        working-directory: prometheus
        run: go run .
