name: Run My Shell Script
on:
  workflow_dispatch:
    inputs:
      script_name:
        description: 'Имя скрипта для запуска'
        required: true
        type: string
        default: 'pipeline-gen.sh'
      repo_url:
        description: 'URL репозитория для клонирования'
        required: true
        type: string
        default: 'https://github.com/prometheus/prometheus.git'
      branch_name:
        description: 'Имя ветки'
        required: false
        type: string
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}  # ← Используем PAT вместо GITHUB_TOKEN
          fetch-depth: 0
      - name: Make script executable
        run: chmod +x ./"${{ github.event.inputs.script_name }}"
      - name: Run the script
        run: ./"${{ github.event.inputs.script_name }}" --repo "${{ github.event.inputs.repo_url }}" --branch "${{ github.event.inputs.branch_name }}"
      - name: Commit and push pipeline.yaml
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ -f pipeline.yaml ]; then
            mkdir -p .github/workflows
            mv pipeline.yaml .github/workflows/pipeline.yaml
            git add .github/workflows/pipeline.yaml
            git commit -m "Update pipeline.yaml from workflow"
            # Используем HTTPS с токеном для пуша
            git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "⚠️ pipeline.yaml не найден, ничего не пушим"
          fi
