name: Run My Shell Script
on:
  workflow_dispatch:
    inputs:
      script_name:
        description: 'Имя скрипта для запуска'
        required: true
        type: string
        default: 'script.sh'
      repo_url:
        description: 'URL репозитория для клонирования'
        required: true
        type: string
        default: 'https://github.com/prometheus/prometheus.git'
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make script executable
        run: chmod +x ./"${{ github.event.inputs.script_name }}"
      - name: Run the script
        run: ./"${{ github.event.inputs.script_name }}" "${{ github.event.inputs.repo_url }}"
      - name: Show output
        run: cat pipeline.yaml
