name: Run My Shell Script
on:
  push:
    branches: [ main ]  # Triggers on push to the main branch
jobs:
  run_script:
    runs-on: ubuntu-latest  # Uses a Linux environment (compatible with .sh scripts)
    steps:
      - uses: actions/checkout@v3  # Step 1: Clones your repo to the runner
      - name: Make script executable
        run: chmod +x ./script.sh  # Step 2: Grants execute permission to your script
      - name: Run the script
        run: ./script.sh "https://github.com/prometheus/prometheus.git"  # Step 3: Executes your shell script
